# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Bithumb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire', '~> 5.5'
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Charts'

  # Pods for Bithumb

  target 'BithumbTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RxTest', '6.5.0'
  pod 'Nimble'
  pod 'RxNimble', subspecs: ['RxBlocking', 'RxTest']
  end

  target 'BithumbUITests' do
    # Pods for testing
  end

end
